# Stixrude Reciprocal Solution Tests

In [1]:
import numpy as np
from thermoengine import core, phases, model

In [2]:
modelDB = model.Database('Stixrude')

In [3]:
opx = modelDB.get_phase('Opx')
cpx = modelDB.get_phase('Cpx')
grt = modelDB.get_phase('Grt')
eps = np.finfo(float).eps
opx.MINVAL = eps*10.
cpx.MINVAL = eps*10.
grt.MINVAL = eps*10.

## Orthopyroxene 

Define component endmember compositions
- enstatite, Mg<sub>2</sub>Si<sub>2</sub>O<sub>6</sub>, component
- ferrosilite, Fe<sub>2</sub>Si<sub>2</sub>O<sub>6</sub>, component
- Mg-Tschermaks, MgAlSiAlO<sub>6</sub>, component
- diopside, CaMgSi<sub>2</sub>O<sub>6</sub>, component
- Fe-Tschermaks, FeAlSiAlO<sub>6</sub>, dependent species
- Ca-Tschermaks, CaAlSiAlO<sub>6</sub>, dependent species
- hedenbergite, CaFeSi<sub>2</sub>O<sub>6</sub>, dependent species

In [4]:
t = 1000 #K
p = 1000 #bars
mol_en = np.array([1.0, 0.0, 0.0, 0.0])
mol_fs = np.array([0.0, 1.0, 0.0, 0.0])
mol_mats = np.array([0.0, 0.0, 1.0, 0.0])
mol_di = np.array([0.0, 0.0, 0.0, 1.0])
mol_fats = np.array([-0.5, 0.5, 1.0, 0.0])
mol_cats = np.array([-1.0, 0.0, 1.0, 1.0])
mol_hd = np.array([-0.5, 0.5, 0.0, 1.0])

### Test composition
Define test composition that is within the reciprocal space but outside the space spaned by positive mole fractions of endmember components.

In [5]:
mol_soln = np.array([-0.3, 0.5, 0.1, 0.7])

In [6]:
(gSoln,sSoln) = (opx.gibbs_energy(t, p, mol=mol_soln), opx.entropy(t, p, mol=mol_soln))
gSoln,sSoln

(-2892154.1081323954, 455.7504069882458)

### Component endmember properties

In [7]:
(gEn,sEn) = (opx.gibbs_energy(t, p, mol=mol_en), opx.entropy(t, p, mol=mol_en))
(gFs,sFs) = (opx.gibbs_energy(t, p, mol=mol_fs), opx.entropy(t, p, mol=mol_fs))
(gMaTs,sMaTs) = (opx.gibbs_energy(t, p, mol=mol_mats), opx.entropy(t, p, mol=mol_mats))
(gDi,sDi) = (opx.gibbs_energy(t, p, mol=mol_di), opx.entropy(t, p, mol=mol_di))

Original Stixrude formulation gives ...

In [8]:
(gEnOrig, sEnOrig) = (-3102147.8019962166, 392.4106374398335)
(gFsOrig, sFsOrig) = (-2470310.9122666894, 463.76231616986473)
(gMaTsOrig, sMaTsOrig) = (-3197089.663787669, 401.32939125408166)
(gDiOrig, sDiOrig) = (-3217537.0835946803, 413.1177618670938)

Comparison with revised formulation ...

In [9]:
print ("{0:s} delta G{1:7.3f} delta S {2:7.3f}".format("En  ", gEn-gEnOrig,sEn-sEnOrig))
print ("{0:s} delta G{1:7.3f} delta S {2:7.3f}".format("Fs  ", gFs-gFsOrig,sFs-sFsOrig))
print ("{0:s} delta G{1:7.3f} delta S {2:7.3f}".format("MaTs", gMaTs-gMaTsOrig,sMaTs-sMaTsOrig))
print ("{0:s} delta G{1:7.3f} delta S {2:7.3f}".format("Di  ", gDi-gDiOrig,sDi-sDiOrig))

En   delta G  0.000 delta S   0.000
Fs   delta G  0.000 delta S   0.000
MaTs delta G -0.000 delta S   0.000
Di   delta G -0.000 delta S   0.000


### Dependent species: FaTs

In [10]:
print('Composition feaible?', opx.test_endmember_comp(mol_fats))
(gFaTs,sFaTs) = (opx.gibbs_energy(t, p, mol=mol_fats), opx.entropy(t, p, mol=mol_fats))
print ('G', gFaTs, 'S', sFaTs) 
print ('Excess model enthalpy for species', gFaTs-(-gEn/2.0+gFs/2.0+gMaTs)) 
print ('Excess model entropy  for species', sFaTs-(-sEn/2.0+sFs/2.0+sMaTs))

Composition feaible? True
G -2881171.2189228903 S 437.0052306190936
Excess model enthalpy for species 1.5366822481155396e-08
Excess model entropy  for species -4.320099833421409e-12


### Dependent species CaTs
This species is feasible in orioginal Stixrude and gives G -3296578.945386117 S 422.03651568133773

In [11]:
print('Composition feaible?', opx.test_endmember_comp(mol_cats))
(gCaTs,sCaTs) = (opx.gibbs_energy(t, p, mol=mol_cats), opx.entropy(t, p, mol=mol_cats))
print ('G', gCaTs, 'S', sCaTs)
print ('Excess model enthalpy for species', gCaTs-(-gEn+gMaTs+gDi))
print ('Excess model entropy  for species', sCaTs-(-sEn+sMaTs+sDi))

Composition feaible? True
G -3296578.945386117 S 422.03651568133773
Excess model enthalpy for species 15900.00000001723
Excess model entropy  for species -5.4001247917767614e-12


### Dependent species Hd

In [12]:
print('Composition feaible?', opx.test_endmember_comp(mol_hd))
(gHd,sHd) = (opx.gibbs_energy(t, p, mol=mol_hd), opx.entropy(t, p, mol=mol_hd))
print ('G', gHd, 'S', sHd)
print ('Excess model enthalpy for species', gHd-(-gEn/2.0+gFs/2.0+gDi))
print ('Excess model entropy  for species', sHd-(-sEn/2.0+sFs/2.0+sDi))

Composition feaible? True
G -2917668.638729902 S 448.79360123210574
Excess model enthalpy for species -16049.999999984168
Excess model entropy  for species -4.206412995699793e-12


### Derivatives of the test composition

In [13]:
mu_soln = opx.gibbs_energy(t, p, mol=mol_soln, deriv={'dmol':1})
mu_soln[0]

array([-3116977.44352854, -2480847.85452831, -3204160.46386834,
       -3237724.81077138])

In [14]:
opx.entropy(t, p, mol=mol_soln, deriv={'dmol':1})

array([[433.09127897, 489.95732613, 469.93532674, 468.68769215]])

In [15]:
opx.gibbs_energy(t, p, mol=mol_soln, deriv={'dmol':2})

array([[[ 78789.93728166, -67999.69597064, -10120.59884971,
          41933.17892807],
        [-67999.69597064,  -9298.86271834, -75254.04872816,
         -55300.27095038],
        [-10120.59884971, -75254.04872816,  26506.07617055,
           4680.67193298],
        [ 41933.17892807, -55300.27095038,   4680.67193298,
          13624.4253769 ]]])

In [16]:
opx.entropy(t, p, mol=mol_soln, deriv={'dmol':2})

array([[[-130.49193728,   38.76769597,  -52.71140115,  -34.23517893],
        [  38.76769597,    2.53686272,   34.89204873,   53.36827095],
        [ -52.71140115,   34.89204873, -100.46807617,    7.78732807],
        [ -34.23517893,   53.36827095,    7.78732807,  -10.72642538]]])

### Test the getAffinityAndComposition

In [17]:
result = opx.affinity_and_comp(t, p, mu_soln[0], debug=True, method='special')

Calling tailored Affinity and Comp routine for OrthopyroxeneStixrude
... Affinity  -5257.525858525474 J/mol
... X [0.19739382 0.27486829 0.23773642 0.00101639]
... Convergence 1
... Iterations 10
... Affinity scalar 10.0
... Estimated error on affinity 0.050219903122524556


In [18]:
result

(-5257.525858525474, array([0.19739382, 0.27486829, 0.23773642, 0.00101639]))

In [19]:
print ('Affinity', result[0])
print ('Composition', result[1], 'Is feasible?', opx.test_endmember_comp(result[1]))
print (opx.compute_formula(t, p, result[1]))

Affinity -5257.525858525474
Composition [0.19739382 0.27486829 0.23773642 0.00101639] Is feasible? True
Ca0.00Mg0.89Fe0.77Al0.67Si1.67O6


## Clinopyroxene

Define component endmember compositions
- diopside, CaMgSi<sub>2</sub>O<sub>6</sub>, component
- hedenbergite, CaFeSi<sub>2</sub>O<sub>6</sub>, component
- enstatite, Mg<sub>2</sub>Si<sub>2</sub>O<sub>6</sub>, component
- Ca-Tschermaks, CaAlSiAlO<sub>6</sub>, component
- Jadeite, NaAlSi<sub>2</sub>O<sub>6</sub>, component
- ferrosilite, Fe<sub>2</sub>Si<sub>2</sub>O<sub>6</sub>, dependent species
- Mg-Tschermaks, MgAlSiAlO<sub>6</sub>, dependent species
- Fe-Tschermaks, FeAlSiAlO<sub>6</sub>, dependent species

In [20]:
t = 1000 #K
p = 1000 #bars
mol_di = np.array([1.0, 0.0, 0.0, 0.0, 0.0])
mol_hd = np.array([0.0, 1.0, 0.0, 0.0, 0.0])
mol_en = np.array([0.0, 0.0, 1.0, 0.0, 0.0])
mol_cats = np.array([0.0, 0.0, 0.0, 1.0, 0.0])
mol_jd = np.array([0.0, 0.0, 0.0, 0.0, 1.0])
mol_fs = np.array([-2.0, 2.0, 1.0, 0.0, 0.0])
mol_mats = np.array([-1.0, 0.0, 1.0, 1.0, 0.0])
mol_fats = np.array([-2.0, 1.0, 1.0, 1.0, 0.0])

### Component endmember properties

In [21]:
(gDi, sDi) = (cpx.gibbs_energy(t, p, mol=mol_di), cpx.entropy(t, p, mol=mol_di))
(gHd, sHd) = (cpx.gibbs_energy(t, p, mol=mol_hd), cpx.entropy(t, p, mol=mol_hd))
(gEn, sEn) = (cpx.gibbs_energy(t, p, mol=mol_en), cpx.entropy(t, p, mol=mol_en))
(gCaTs, sCaTs) = (cpx.gibbs_energy(t, p, mol=mol_cats), cpx.entropy(t, p, mol=mol_cats))
(gJd, sJd) = (cpx.gibbs_energy(t, p, mol=mol_jd), cpx.entropy(t, p, mol=mol_jd))

Original Stixrude formulation gives ...

In [22]:
(gDiOrig, sDiOrig) = (-3224185.546973538, 402.7786672101605)
(gHdOrig, sHdOrig) = (-2902313.7637790395, 441.79280536887234)
(gEnOrig, sEnOrig) = (-3096333.69539603, 395.917686128514)
(gCaTsOrig, sCaTsOrig) = (-3321770.992334972, 405.9295393600187)
(gJdOrig, sJdOrig) = (-3042270.9934835685, 389.57303311062225)

Comparison with revised formulation ...  
(original Stixrude has Al,Si entropy on the tetrahedral site; revision does not)

In [24]:
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("Di  ", gDi-gDiOrig, sDi-sDiOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("Hd  ", gHd-gHdOrig, sHd-sHdOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("En  ", gEn-gEnOrig, sEn-sEnOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("CaTs", gCaTs-gCaTsOrig, sCaTs-sCaTsOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("Jd  ", gJd-gJdOrig, sJd-sJdOrig))
print ("")
print ("2Rln2 is {0:7.3f}, -2RTln2 is {1:10.3f}".format(8.3143*2.0*np.log(2.0), -8.3143*t*2.0*np.log(2.0)))

Di   delta G      0.000 delta S  -0.000
Hd   delta G      0.000 delta S  -0.000
En   delta G      0.000 delta S  -0.000
CaTs delta G  11526.067 delta S -11.526
Jd   delta G      0.000 delta S  -0.000

2Rln2 is  11.526, -2RTln2 is -11526.067


### Dependent species Fs

In [25]:
print('Composition feaible?', cpx.test_endmember_comp(mol_fs))
(gFs,sFs) = (cpx.gibbs_energy(t, p, mol=mol_fs), cpx.entropy(t, p, mol=mol_fs))
print ('G', gFs, 'S', sFs) 
print ('Excess model enthalpy for species', gFs-(-2.0*gDi+2.0*gHd+gEn)) 
print ('Excess model entropy  for species', sFs-(-2.0*sDi+2.0*sHd+sEn))

Composition feaible? True
G -2452590.1290070144 S 473.9459624459321
Excess model enthalpy for species 1.955777406692505e-08
Excess model entropy  for species -6.0822458181064576e-12


### Dependent species MaTs
Feasible in Stixrude original and gives G -3185598.505836813 S 399.0685582783678

In [26]:
print('Composition feaible?', cpx.test_endmember_comp(mol_mats))
(gMaTs,sMaTs) = (cpx.gibbs_energy(t, p, mol=mol_mats), cpx.entropy(t, p, mol=mol_mats))
print ('G', gMaTs, 'S', sMaTs) 
print ('Excess model enthalpy for species', gMaTs-(-gDi+gEn+gCaTs)) 
print ('Excess model entropy  for species', sMaTs-(-sDi+sEn+sCaTs))

Composition feaible? True
G -3174072.4386301544 S 387.54249107170926
Excess model enthalpy for species 8320.634920651093
Excess model entropy  for species -3.751665644813329e-12


### Dependent species FaTs

In [27]:
print('Composition feaible?', cpx.test_endmember_comp(mol_fats))
(gFaTs,sFaTs) = (cpx.gibbs_energy(t, p, mol=mol_fats), cpx.entropy(t, p, mol=mol_fats))
print ('G', gFaTs, 'S', sFaTs) 
print ('Excess model enthalpy for species', gFaTs-(-2.0*gDi+gHd+gEn+gCaTs)) 
print ('Excess model entropy  for species', sFaTs-(-2.0*sDi+sHd+sEn+sCaTs))

Composition feaible? True
G -2863756.210991202 S 426.5566292304177
Excess model enthalpy for species -3234.920634894166
Excess model entropy  for species -7.73070496506989e-12


### Test composition
Define test composition that is within the reciprocal space but outside the space spaned by positive mole fractions of endmember components:  

In [28]:
mol_soln = np.array([-1.2, 1.3, 0.7, 0.05, 0.05])
print (cpx.compute_formula(t, p, mol_soln))

Na0.06Ca0.17Mg0.22Fe1.44Al0.17Si1.94O6


In [29]:
print('Composition feaible?', cpx.test_endmember_comp(mol_soln))
(gSoln,sSoln) = (cpx.gibbs_energy(t, p, mol=mol_soln), cpx.entropy(t, p, mol=mol_soln))
gSoln,sSoln

Composition feaible? True


(-2400297.198968812, 419.74374433414135)

### Derivatives of the test composition

In [30]:
mu_soln = cpx.gibbs_energy(t, p, mol=mol_soln, deriv={'dmol':1})
mu_soln[0]

array([-3237629.19648135, -2903352.95403009, -3126740.55906787,
       -3329279.20916869, -3113101.95893466])

In [31]:
cpx.entropy(t, p, mol=mol_soln, deriv={'dmol':1})

array([[435.12330158, 472.35948429, 459.77664527, 468.63900733,
        486.72752983]])

In [32]:
cpx.gibbs_energy(t, p, mol=mol_soln, deriv={'dmol':2})

array([[[ 4.20570898e+04,  1.42878127e+04,  5.00254168e+04,
          2.08401538e+04,  3.63678033e+04],
        [ 1.42878127e+04,  1.47728662e+04, -2.48487735e+04,
         -2.33962441e+04,  1.78996055e+02],
        [ 5.00254168e+04, -2.48487735e+04,  1.31555396e+05,
          4.88864468e+04,  1.18736969e+04],
        [ 2.08401538e+04, -2.33962441e+04,  4.88864468e+04,
          2.10344420e+04,  1.99679926e+05],
        [ 3.63678033e+04,  1.78996055e+02,  1.18736969e+04,
          1.99679926e+05,  2.81666810e+05]]])

In [33]:
cpx.entropy(t, p, mol=mol_soln, deriv={'dmol':2})

array([[[ -78.93706023,  -48.08654846,  -50.10692077,  -59.43132022,
           -2.98774331],
        [ -48.08654846,  -45.49036727,   27.84850428,  -43.86859538,
           12.57498153],
        [ -50.10692077,   27.84850428, -143.03355544,    9.48504131,
           10.49995155],
        [ -59.43132022,  -43.86859538,    9.48504131, -115.5989305 ,
          -99.61843817],
        [  -2.98774331,   12.57498153,   10.49995155,  -99.61843817,
         -225.44135359]]])

### Test the getAffinityAndComposition

In [34]:
result = cpx.affinity_and_comp(t, p, mu_soln[0], debug=True, method='special')

Calling tailored Affinity and Comp routine for ClinopyroxeneStixrude
... Affinity  -1619.8236751879685 J/mol
... X [0.12639363 0.68826231 0.00279241 0.08240178 0.00205123]
... Convergence 1
... Iterations 15
... Affinity scalar 10.0
... Estimated error on affinity 0.08923770030742162


In [35]:
result

(-1619.8236751879685,
 array([0.12639363, 0.68826231, 0.00279241, 0.08240178, 0.00205123]))

In [36]:
print ('Affinity', result[0])
print ('Composition', result[1], 'Is feasible?', cpx.test_endmember_comp(result[1]))
print (cpx.compute_formula(t, p, result[1]))

Affinity -1619.8236751879685
Composition [0.12639363 0.68826231 0.00279241 0.08240178 0.00205123] Is feasible? True
Na0.00Ca0.99Mg0.15Fe0.76Al0.19Si1.91O6


## Garnet

Define component endmember compositions
- pyrope, Mg<sub>3</sub>Al<sub>2</sub>Si<sub>3</sub>O<sub>12</sub>, component
- almandine, Fe<sub>3</sub>Al<sub>2</sub>Si<sub>3</sub>O<sub>12</sub>, component
- grossular, Ca<sub>3</sub>Al<sub>2</sub>Si<sub>3</sub>O<sub>12</sub>, component
- majorite, Mg<sub>3</sub>SiMgSi<sub>3</sub>O<sub>12</sub>, component
- Na-majorite, Na<sub>2</sub>AlSiAlSi<sub>3</sub>O<sub>12</sub>, component
- Fe-majorite, Fe<sub>3</sub>SiFeSi<sub>3</sub>O<sub>12</sub>, dependent species

In [37]:
t = 1000 #K
p = 1000 #bars
mol_py = np.array([1.0, 0.0, 0.0, 0.0, 0.0])
mol_al = np.array([0.0, 1.0, 0.0, 0.0, 0.0])
mol_gr = np.array([0.0, 0.0, 1.0, 0.0, 0.0])
mol_mj = np.array([0.0, 0.0, 0.0, 1.0, 0.0])
mol_na = np.array([0.0, 0.0, 0.0, 0.0, 1.0])
mol_fmj = np.array([-4.0/3.0, 4.0/3.0, 0.0, 1.0, 0.0])

### Component endmember properties

In [38]:
(gPy, sPy) = (grt.gibbs_energy(t, p, mol=mol_py), grt.entropy(t, p, mol=mol_py))
(gAl, sAl) = (grt.gibbs_energy(t, p, mol=mol_al), grt.entropy(t, p, mol=mol_al))
(gGr, sGr) = (grt.gibbs_energy(t, p, mol=mol_gr), grt.entropy(t, p, mol=mol_gr))
(gMj, sMj) = (grt.gibbs_energy(t, p, mol=mol_mj), grt.entropy(t, p, mol=mol_mj))
(gNa, sNa) = (grt.gibbs_energy(t, p, mol=mol_na), grt.entropy(t, p, mol=mol_na))

Original Stixrude formulation gives ...

In [39]:
(gPyOrig, sPyOrig) = (-6310902.894875664, 778.8357696040242)
(gAlOrig, sAlOrig) = (-5383284.440223204, 870.4557640298455)
(gGrOrig, sGrOrig) = (-6651262.435797561, 779.1122322634751)
(gMjOrig, sMjOrig) = (-6065999.844062188, 778.8368052509709)
(gNaOrig, sNaOrig) = (-5882508.634123785, 753.6359891393868)

Comparison with revised formulation ...  
(original Stixrude does not allow Fe on octahedral site and assumes that the octahedral site splits, so that mixed site populations do not contribute to the entropy)

In [40]:
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("Py  ", gPy-gPyOrig, sPy-sPyOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("Al  ", gAl-gAlOrig, sAl-sAlOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("Gr  ", gGr-gGrOrig, sGr-sGrOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("Mj  ", gMj-gMjOrig, sMj-sMjOrig))
print ("{0:s} delta G {1:10.3f} delta S {2:7.3f}".format("NaMj", gNa-gNaOrig, sNa-sNaOrig))
print ("")
print ("2Rln2 is {0:7.3f}, -2RTln2 is {1:10.3f}".format(8.3143*2.0*np.log(2.0), -8.3143*t*2.0*np.log(2.0)))

Py   delta G      0.000 delta S   0.000
Al   delta G     -0.000 delta S   0.000
Gr   delta G      0.000 delta S   0.000
Mj   delta G -11526.067 delta S  11.526
NaMj delta G -11526.067 delta S  11.526

2Rln2 is  11.526, -2RTln2 is -11526.067


### Dependent species Fe-majorite

In [34]:
print('Composition feaible?', grt.test_endmember_comp(mol_fmj))
(gFmj,sFmj) = (grt.gibbs_energy(t, p, mol=mol_fmj), grt.entropy(t, p, mol=mol_fmj))
print ('G', gFmj, 'S', sFmj) 
print ('Excess model enthalpy for species', gFmj-(-4.0*gPy/3.0+4.0*gAl/3.0+gMj)) 
print ('Excess model entropy  for species', sFmj-(-4.0*sPy/3.0+4.0*sAl/3.0+sMj))

Composition feaible? True
G -4869101.305065533 S 912.5228650253819
Excess model enthalpy for species -28399.99999996554
Excess model entropy  for species -1.0459189070388675e-11


### Test composition
Define test composition that is within the reciprocal space but outside the space spaned by positive mole fractions of endmember components: 

In [35]:
mol_soln = np.array([-4.0/3.0+0.2, 4.0/3.0-0.1, 0.02, 0.86, 0.02])
print (grt.compute_formula(t, p, mol_soln))

Na0.04Ca0.06Mg0.04Fe3.70Al0.28Si3.86O12


In [36]:
print('Composition feaible?', grt.test_endmember_comp(mol_soln))
(gSoln,sSoln) = (grt.gibbs_energy(t, p, mol=mol_soln), grt.entropy(t, p, mol=mol_soln))
gSoln,sSoln

Composition feaible? True


(-4998077.972998836, 914.5085439869182)

### Derivatives of the test composition

In [37]:
mu_soln = grt.gibbs_energy(t, p, mol=mol_soln, deriv={'dmol':1})
mu_soln[0]

array([-6419676.24818131, -5398054.08102949, -6746442.85048883,
       -6234318.05302791, -5983431.91937544])

In [38]:
grt.entropy(t, p, mol=mol_soln, deriv={'dmol':1})

array([[ 926.96992291,  929.15809198,  957.59522124, 1015.08747564,
         968.96162296]])

In [40]:
grt.gibbs_energy(t, p, mol=mol_soln, deriv={'dmol':2})

array([[[1776964.37130167,  -41826.73014705,  100136.58811443,
         2317555.79357349,   22060.43426828],
        [ -41826.73014705,  -35693.15572537,  -23867.12438493,
         -171266.03389983,  -71943.27823108],
        [ 100136.58811443,  -23867.12438493, 1153493.35759845,
         -144067.70899304,  136812.42791737],
        [2317555.79357349, -171266.03389983, -144067.70899304,
         3191404.89842469,  -27787.64927909],
        [  22060.43426828,  -71943.27823108,  136812.42791737,
          -27787.64927909, 1098767.19501103]]])

In [41]:
grt.entropy(t, p, mol=mol_soln, deriv={'dmol':2})

array([[[-1855.6859713 ,   -17.97686985,  -145.82018811, -2333.07939357,
           -81.86403427],
        [  -17.97686985,    -5.19244427,   -32.89847562,   153.3604339 ,
            31.05767823],
        [ -145.82018811,   -32.89847562, -1226.1389576 ,   168.28210899,
          -193.57802792],
        [-2333.07939357,   153.3604339 ,   168.28210899, -3186.33049842,
             9.88204928],
        [  -81.86403427,    31.05767823,  -193.57802792,     9.88204928,
         -1139.65279501]]])

### Test the getAffinityAndComposition

In [42]:
result = grt.affinity_and_comp(t, p, mu_soln[0], debug=True, method='special')

Calling tailored Affinity and Comp routine for GarnetStixrude
... Affinity  296.1965119034576 J/mol
... X [1.33437427e-02 8.89634698e-02 2.00715333e-02 1.44416327e-05
 8.21251727e-03]
... Convergence 1
... Iterations 40
... Affinity scalar 20.0
... Estimated error on affinity 0.8873941271012882


In [43]:
result

(296.1965119034576,
 array([1.33437427e-02, 8.89634698e-02, 2.00715333e-02, 1.44416327e-05,
        8.21251727e-03]))

In [44]:
print ('Affinity', result[0])
print ('Composition', result[1], 'Is feasible?', grt.test_endmember_comp(result[1]))
print (grt.compute_formula(t, p, result[1]))

Affinity 296.1965119034576
Composition [1.33437427e-02 8.89634698e-02 2.00715333e-02 1.44416327e-05
 8.21251727e-03] Is feasible? True
Na0.13Ca0.46Mg0.31Fe0.27Al2.00Si3.00O12
